import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import tenantsRouter from "./tenants";
import leadsRouter from "./leads";
import quotesRouter from "./quotes";
import paymentLinksRouter from "./paymentLinks";
import projectsRouter from "./projects";
import customersRouter from "./customers";
import contentRouter from "./content";
import blogRouter from "./blog";
import visualiserRouter from "./visualiser";
import contactRouter from "./contact";
import dashboardRouter from "./dashboard";
import publicRouter from "./public";
import renderRouter from "./render";
import publicPaymentsRouter from "./publicPayments";
import publicJobsRouter from "./publicJobs";
import teamMessagesRouter from "./teamMessages";
import accountingRouter from "./accounting";
import usersRouter from "./users";
import settingsRouter from "./settings";
import emailsRouter from "./emails";
import supportRouter from "./support";
import certificatesRouter from "./certificates";
import certificatesIssueRouter from "./certificatesIssue";
import certificatePhotosRouter from "./certificatePhotos";
import jobsRouter from "./jobs";
import invoicesRouter from "./invoices";
import expensesRouter from "./expenses";
import automationsRouter from "./automations";
import scheduleRouter from "./schedule";
import moneyRouter from "./money";
import signupRouter from "./signup";
import billingRouter from "./billing";
import filesRouter from "./files";
import propertiesRouter from "./properties";
import assistantRouter from "./assistant";

const router: IRouter = Router();

router.use(healthRouter);
router.use(certificatesRouter);
router.use(certificatesIssueRouter);
router.use(certificatePhotosRouter);
router.use(jobsRouter);
router.use(invoicesRouter);
router.use(expensesRouter);
router.use(automationsRouter);
router.use(scheduleRouter);
router.use(moneyRouter);
router.use(signupRouter);
router.use(billingRouter);
router.use(filesRouter);
router.use(propertiesRouter);
router.use(assistantRouter);
router.use(storageRouter);
router.use("/auth", authRouter);
router.use(tenantsRouter);
router.use(leadsRouter);
router.use(quotesRouter);
router.use(paymentLinksRouter);
router.use(projectsRouter);
router.use(customersRouter);
router.use(contentRouter);
router.use(blogRouter);
router.use(visualiserRouter);
router.use(contactRouter);
router.use(dashboardRouter);
router.use(publicRouter);
router.use(renderRouter);
router.use(publicPaymentsRouter);
router.use(publicJobsRouter);
router.use(teamMessagesRouter);
router.use(accountingRouter);
router.use(usersRouter);
router.use(settingsRouter);
router.use(emailsRouter);
router.use(supportRouter);

export default router;
