import { Router } from "express";
import { randomUUID } from "node:crypto";
import { db } from "@workspace/db";
import { paymentLinksTable, quotesTable, quoteItemsTable, tenantsTable, tenantSettingsTable } from "@workspace/db";
import { eq, and, sql } from "drizzle-orm";
import { requireTenantAccess, tenantFilter } from "../middlewares/auth";
import { buildPayUrl, resolveQuoteRecipient, requireOwnedQuote } from "./quotes";
import { fireNotification } from "../lib/notifications";
import { sendEmail, buildPaymentRequestEmail } from "../lib/email";
import { buildSmtpConfig, buildBrandConfig } from "../lib/settingsHelpers";

const router = Router();

async function attachPayUrl<T extends { tenantId: number; token: string }>(link: T): Promise<T & { url: string }> {
  const tenantRows = await db.select({ slug: tenantsTable.slug, customDomain: tenantsTable.customDomain })
    .from(tenantsTable).where(eq(tenantsTable.id, link.tenantId)).limit(1);
  const tenant = tenantRows[0];
  return { ...link, url: buildPayUrl({ customDomain: tenant?.customDomain, tenantSlug: tenant?.slug ?? "", token: link.token }) };
}

// ─── Quote-linked payment links ────────────────────────────────────────────

router.get("/quotes/:id/payment-links", requireTenantAccess, async (req, res) => {
  try {
    const quoteId = await requireOwnedQuote(req, res);
    if (quoteId === null) return;
    const links = await db.select().from(paymentLinksTable)
      .where(eq(paymentLinksTable.quoteId, quoteId))
      .orderBy(sql`${paymentLinksTable.createdAt} desc`);
    res.json(await Promise.all(links.map(attachPayUrl)));
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.post("/quotes/:id/payment-links", requireTenantAccess, async (req, res) => {
  try {
    const quoteId = await requireOwnedQuote(req, res);
    if (quoteId === null) return;
    const amount = Number(req.body.amount);
    if (!Number.isFinite(amount) || amount <= 0) {
      res.status(400).json({ error: "amount must be a positive number" });
      return;
    }
    const q = await db.select({ tenantId: quotesTable.tenantId }).from(quotesTable).where(eq(quotesTable.id, quoteId)).limit(1);
    const link = await db.insert(paymentLinksTable).values({
      tenantId: q[0].tenantId,
      quoteId,
      token: randomUUID(),
      amount: amount.toFixed(2),
      isAutoGenerated: false,
      idempotencyKey: randomUUID(),
    }).returning();
    res.status(201).json(await attachPayUrl(link[0]));
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

// ─── Standalone payment links (no quote — e.g. a phone sale) ──────────────

router.get("/payment-links", requireTenantAccess, async (req, res) => {
  try {
    const links = await db.select().from(paymentLinksTable)
      .where(tenantFilter(req, paymentLinksTable.tenantId))
      .orderBy(sql`${paymentLinksTable.createdAt} desc`);
    res.json(await Promise.all(links.map(attachPayUrl)));
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.post("/payment-links", requireTenantAccess, async (req, res) => {
  try {
    const amount = Number(req.body.amount);
    if (!Number.isFinite(amount) || amount <= 0) {
      res.status(400).json({ error: "amount must be a positive number" });
      return;
    }
    const tenantId = req.authUser?.tenantId ?? -1;
    const link = await db.insert(paymentLinksTable).values({
      tenantId,
      token: randomUUID(),
      amount: amount.toFixed(2),
      isAutoGenerated: false,
      idempotencyKey: randomUUID(),
      customerName: req.body.customerName || null,
      customerEmail: req.body.customerEmail || null,
      customerPhone: req.body.customerPhone || null,
      customerAddress: req.body.customerAddress || null,
    }).returning();
    res.status(201).json(await attachPayUrl(link[0]));
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

// ─── Unified send — emails the customer, works for quote-linked or standalone ──

router.post("/payment-links/:id/send", requireTenantAccess, async (req, res) => {
  try {
    const rows = await db.select().from(paymentLinksTable)
      .where(and(eq(paymentLinksTable.id, Number(req.params.id)), tenantFilter(req, paymentLinksTable.tenantId)))
      .limit(1);
    const link = rows[0];
    if (!link) { res.status(404).json({ error: "Not found" }); return; }

    if (link.quoteId) {
      const quoteRows = await db.select().from(quotesTable).where(eq(quotesTable.id, link.quoteId)).limit(1);
      const quote = quoteRows[0];
      if (!quote) { res.status(404).json({ error: "Quote not found" }); return; }

      const recipient = await resolveQuoteRecipient(quote);
      if (!recipient.customerEmail) { res.status(400).json({ error: "This quote has no customer email on file" }); return; }

      const linkAmount = Number(link.amount);
      const quoteTotal = Number(quote.total);
      const remainingBalance = linkAmount < quoteTotal ? `£${(quoteTotal - linkAmount).toFixed(2)}` : undefined;

      const withUrl = await attachPayUrl(link);
      if (quote.status !== "Sent") {
        await db.update(quotesTable).set({ status: "Sent" }).where(eq(quotesTable.id, quote.id));
      }

      fireNotification({
        tenantId: link.tenantId,
        event: "quote_sent",
        ...recipient,
        reference: quote.reference,
        paymentLinkUrl: withUrl.url,
        amount: `£${linkAmount.toFixed(2)}`,
        remainingBalance,
      });

      res.json(withUrl);
    } else {
      if (!link.customerEmail) { res.status(400).json({ error: "This payment link has no customer email on file" }); return; }

      const settingsRows = await db.select().from(tenantSettingsTable).where(eq(tenantSettingsTable.tenantId, link.tenantId)).limit(1);
      const tenantRows = await db.select().from(tenantsTable).where(eq(tenantsTable.id, link.tenantId)).limit(1);
      const settings = settingsRows[0];
      const tenant = tenantRows[0];
      const smtp = buildSmtpConfig(settings as any);
      const withUrl = await attachPayUrl(link);

      if (smtp) {
        sendEmail(buildPaymentRequestEmail({
          brand: buildBrandConfig(tenant as any, settings as any),
          firstName: link.customerName || "there",
          amount: `£${Number(link.amount).toFixed(2)}`,
          paymentLinkUrl: withUrl.url,
          to: link.customerEmail,
        }), smtp).catch(e => req.log.error({ err: e }, "Failed to send standalone payment request email"));
      }

      res.json(withUrl);
    }
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

export default router;
