import { Router } from "express";
import { randomUUID } from "node:crypto";
import { db } from "@workspace/db";
import { quotesTable, quoteItemsTable, projectsTable, leadsTable, customersTable, tenantsTable, paymentLinksTable } from "@workspace/db";
import { eq, and, sql } from "drizzle-orm";
import { requireTenantAccess, tenantFilter } from "../middlewares/auth";
import { fireNotification } from "../lib/notifications";
import { sanitizeUpdate } from "../lib/sanitizeUpdate";

const router = Router();

const PLATFORM_BASE_URL = process.env.PUBLIC_BASE_URL || "https://bizzflowuk.com";

/** Builds the customer-facing URL for a payment link, honoring a tenant's custom domain if set. */
export function buildPayUrl(opts: { customDomain?: string | null; tenantSlug: string; token: string }): string {
  if (opts.customDomain) return `https://${opts.customDomain}/pay/${opts.token}`;
  return `${PLATFORM_BASE_URL}/site/${opts.tenantSlug}/pay/${opts.token}`;
}

/** Resolves the customer name/email/phone to notify for a quote, from its linked customer or lead. */
export async function resolveQuoteRecipient(quote: { customerId: number | null; leadId: number | null }): Promise<{
  firstName?: string; lastName?: string; customerEmail?: string; customerPhone?: string;
}> {
  if (quote.customerId) {
    const rows = await db.select().from(customersTable).where(eq(customersTable.id, quote.customerId)).limit(1);
    const c = rows[0];
    if (c) return { firstName: c.firstName, lastName: c.lastName, customerEmail: c.email ?? undefined, customerPhone: c.phone ?? undefined };
  } else if (quote.leadId) {
    const rows = await db.select().from(leadsTable).where(eq(leadsTable.id, quote.leadId)).limit(1);
    const l = rows[0];
    if (l) return { firstName: l.firstName ?? undefined, lastName: l.lastName ?? undefined, customerEmail: l.email ?? undefined, customerPhone: l.phone ?? undefined };
  }
  return {};
}

router.get("/quotes", requireTenantAccess, async (req, res) => {
  try {
    const quotes = await db.select().from(quotesTable)
      .where(tenantFilter(req, quotesTable.tenantId))
      .orderBy(sql`${quotesTable.createdAt} desc`);
    res.json(quotes);
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.post("/quotes", requireTenantAccess, async (req, res) => {
  try {
    const ref = req.body.reference ?? `QUO-${Date.now()}`;
    const q = await db.insert(quotesTable).values({ ...req.body, reference: ref, tenantId: req.authUser?.tenantId ?? -1 }).returning();
    res.status(201).json(q[0]);
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.get("/quotes/:id", requireTenantAccess, async (req, res) => {
  try {
    const q = await db.select().from(quotesTable)
      .where(and(eq(quotesTable.id, Number(req.params.id)), tenantFilter(req, quotesTable.tenantId)))
      .limit(1);
    if (!q.length) { res.status(404).json({ error: "Not found" }); return; }
    res.json(q[0]);
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.patch("/quotes/:id", requireTenantAccess, async (req, res) => {
  try {
    const before = await db.select().from(quotesTable)
      .where(and(eq(quotesTable.id, Number(req.params.id)), tenantFilter(req, quotesTable.tenantId)))
      .limit(1);
    const q = await db.update(quotesTable).set(sanitizeUpdate(req.body))
      .where(and(eq(quotesTable.id, Number(req.params.id)), tenantFilter(req, quotesTable.tenantId)))
      .returning();
    if (!q.length) { res.status(404).json({ error: "Not found" }); return; }
    res.json(q[0]);

    const newStatus = req.body.status;
    if (newStatus && before[0]?.status !== newStatus) {
      const recipient = await resolveQuoteRecipient(q[0]);

      if (newStatus === "Sent") {
        let paymentLinkUrl: string | undefined;
        try {
          const tenantRows = await db.select({ slug: tenantsTable.slug, customDomain: tenantsTable.customDomain })
            .from(tenantsTable).where(eq(tenantsTable.id, q[0].tenantId)).limit(1);
          const tenant = tenantRows[0];
          if (tenant) {
            // Only one auto-generated link should be "live" at a time — cancel any prior pending one first.
            await db.update(paymentLinksTable)
              .set({ status: "Cancelled" })
              .where(and(eq(paymentLinksTable.quoteId, q[0].id), eq(paymentLinksTable.isAutoGenerated, true), eq(paymentLinksTable.status, "Pending")));

            const token = randomUUID();
            await db.insert(paymentLinksTable).values({
              tenantId: q[0].tenantId,
              quoteId: q[0].id,
              token,
              amount: q[0].total,
              isAutoGenerated: true,
              idempotencyKey: randomUUID(),
            });
            paymentLinkUrl = buildPayUrl({ customDomain: tenant.customDomain, tenantSlug: tenant.slug, token });
          }
        } catch (linkErr) { req.log.error(linkErr, "Failed to auto-generate payment link"); }

        fireNotification({ tenantId: q[0].tenantId, event: "quote_sent", ...recipient, reference: q[0].reference, paymentLinkUrl });
      } else if (newStatus === "Accepted") {
        fireNotification({ tenantId: q[0].tenantId, event: "quote_accepted", ...recipient, reference: q[0].reference });
      }
    }
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.delete("/quotes/:id", requireTenantAccess, async (req, res) => {
  try {
    await db.delete(quotesTable)
      .where(and(eq(quotesTable.id, Number(req.params.id)), tenantFilter(req, quotesTable.tenantId)));
    res.status(204).send();
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.post("/quotes/:id/convert-to-project", requireTenantAccess, async (req, res) => {
  try {
    const q = await db.select().from(quotesTable)
      .where(and(eq(quotesTable.id, Number(req.params.id)), tenantFilter(req, quotesTable.tenantId)))
      .limit(1);
    if (!q.length) { res.status(404).json({ error: "Not found" }); return; }
    const project = await db.insert(projectsTable).values({
      tenantId: q[0].tenantId,
      quoteId: q[0].id,
      customerId: q[0].customerId ?? undefined,
      title: `Project from ${q[0].reference}`,
    }).returning();
    await db.update(quotesTable).set({ status: "Accepted" }).where(eq(quotesTable.id, q[0].id));
    res.status(201).json(project[0]);

    const recipient = await resolveQuoteRecipient(q[0]);
    fireNotification({ tenantId: q[0].tenantId, event: "quote_accepted", ...recipient, reference: q[0].reference });
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

/** Confirms :id refers to a quote the caller's tenant actually owns (or bypasses for SUPER_ADMIN). */
async function requireOwnedQuote(req: any, res: any): Promise<number | null> {
  const quote = await db.select({ id: quotesTable.id }).from(quotesTable)
    .where(and(eq(quotesTable.id, Number(req.params.id)), tenantFilter(req, quotesTable.tenantId)))
    .limit(1);
  if (!quote.length) {
    res.status(404).json({ error: "Not found" });
    return null;
  }
  return quote[0].id;
}

async function attachPayUrl<T extends { tenantId: number; token: string }>(link: T): Promise<T & { url: string }> {
  const tenantRows = await db.select({ slug: tenantsTable.slug, customDomain: tenantsTable.customDomain })
    .from(tenantsTable).where(eq(tenantsTable.id, link.tenantId)).limit(1);
  const tenant = tenantRows[0];
  return { ...link, url: buildPayUrl({ customDomain: tenant?.customDomain, tenantSlug: tenant?.slug ?? "", token: link.token }) };
}

router.get("/quotes/:id/payment-links", requireTenantAccess, async (req, res) => {
  try {
    const quoteId = await requireOwnedQuote(req, res);
    if (quoteId === null) return;
    const links = await db.select().from(paymentLinksTable)
      .where(eq(paymentLinksTable.quoteId, quoteId))
      .orderBy(sql`${paymentLinksTable.createdAt} desc`);
    res.json(await Promise.all(links.map(attachPayUrl)));
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.post("/quotes/:id/payment-links", requireTenantAccess, async (req, res) => {
  try {
    const quoteId = await requireOwnedQuote(req, res);
    if (quoteId === null) return;
    const amount = Number(req.body.amount);
    if (!Number.isFinite(amount) || amount <= 0) {
      res.status(400).json({ error: "amount must be a positive number" });
      return;
    }
    const q = await db.select({ tenantId: quotesTable.tenantId }).from(quotesTable).where(eq(quotesTable.id, quoteId)).limit(1);
    const link = await db.insert(paymentLinksTable).values({
      tenantId: q[0].tenantId,
      quoteId,
      token: randomUUID(),
      amount: amount.toFixed(2),
      isAutoGenerated: false,
      idempotencyKey: randomUUID(),
    }).returning();
    res.status(201).json(await attachPayUrl(link[0]));
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.get("/quotes/:id/items", requireTenantAccess, async (req, res) => {
  try {
    const quoteId = await requireOwnedQuote(req, res);
    if (quoteId === null) return;
    const items = await db.select().from(quoteItemsTable)
      .where(eq(quoteItemsTable.quoteId, quoteId))
      .orderBy(quoteItemsTable.sortOrder);
    res.json(items);
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.post("/quotes/:id/items", requireTenantAccess, async (req, res) => {
  try {
    const quoteId = await requireOwnedQuote(req, res);
    if (quoteId === null) return;
    const item = await db.insert(quoteItemsTable).values({ ...req.body, quoteId }).returning();
    res.status(201).json(item[0]);
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.patch("/quotes/:id/items/:itemId", requireTenantAccess, async (req, res) => {
  try {
    const quoteId = await requireOwnedQuote(req, res);
    if (quoteId === null) return;
    const item = await db.update(quoteItemsTable).set(sanitizeUpdate(req.body))
      .where(and(eq(quoteItemsTable.id, Number(req.params.itemId)), eq(quoteItemsTable.quoteId, quoteId)))
      .returning();
    if (!item.length) { res.status(404).json({ error: "Not found" }); return; }
    res.json(item[0]);
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.delete("/quotes/:id/items/:itemId", requireTenantAccess, async (req, res) => {
  try {
    const quoteId = await requireOwnedQuote(req, res);
    if (quoteId === null) return;
    await db.delete(quoteItemsTable)
      .where(and(eq(quoteItemsTable.id, Number(req.params.itemId)), eq(quoteItemsTable.quoteId, quoteId)));
    res.status(204).send();
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

export default router;
