import { pgTable, text, serial, timestamp, integer, boolean, pgEnum, numeric, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { tenantsTable } from "./tenants";
import { quotesTable } from "./quotes";

export const paymentLinkStatusEnum = pgEnum("payment_link_status", ["Pending", "Paid", "Failed", "Expired", "Cancelled"]);

export const paymentLinksTable = pgTable("payment_links", {
  id: serial("id").primaryKey(),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id),
  quoteId: integer("quote_id").references(() => quotesTable.id),
  token: text("token").notNull().unique(),
  amount: numeric("amount", { precision: 10, scale: 2 }).notNull(),
  // Standalone (no linked quote) — e.g. a phone sale Mark wants to charge directly.
  customerName: text("customer_name"),
  customerEmail: text("customer_email"),
  customerPhone: text("customer_phone"),
  customerAddress: text("customer_address"),
  currency: text("currency").notNull().default("GBP"),
  status: paymentLinkStatusEnum("status").notNull().default("Pending"),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  idempotencyKey: text("idempotency_key").notNull(),
  squarePaymentId: text("square_payment_id"),
  failureReason: text("failure_reason"),
  paidAt: timestamp("paid_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => [
  index("payment_links_tenant_id_idx").on(table.tenantId),
  index("payment_links_quote_id_idx").on(table.quoteId),
  index("payment_links_token_idx").on(table.token),
]);

export const insertPaymentLinkSchema = createInsertSchema(paymentLinksTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertPaymentLink = z.infer<typeof insertPaymentLinkSchema>;
export type PaymentLink = typeof paymentLinksTable.$inferSelect;
